export const metadata = {
  title: " Installation Page | Play store app ",
  description: "Generated by create play store app",
};

const page = () => {
    return (
        <div>
             Installation page
        </div>
    );
};

export default page;