
export const metadata = {
  title: " Apps Page | Play store app ",
  description: " Generated by create play store app ",
};
const page = () => {
    return (
        <div>
            apps page
        </div>
    );
};

export default page;