import TrendingApps from "@/components/homepage/TrendingApps";

export const metadata = {
  title: " Apps Page | Play store app ",
  description: " Generated by create play store app ",
};
const AppsPage = () => {
    return (
        <div>
            apps page
            <TrendingApps from="apps"/>
        </div>
    );
};

export default AppsPage;